### ISSUE TITLE
Merge of Dash v0.12.1.0 Tasks

### ISSUE THREAD

**Issue by Mrs-X** [Mrs-X/PIVX#3]
@Fuzzbawls

**Done:**
**Files in process:**

<hr>
@jonspock

**Done:**

- Use NetworkIDString as string instead of Enum NetworkID, some compilation fixes, some uint256 changes, remove some duplicate lines. Files modified: `activemasternode.cpp, chain.h, chainparams.cpp, chainparams.h, chainparamsbase.h, checkpoints.h, coins.cpp, coins.h, compat/byteswap.h, hash.h, kernel.cpp, main.cpp, main.h, masternode-budget.cpp, masternode-budget.h, masternode.cpp, masternodeconfig.cpp, masternodeman.cpp, masternodeman.h, net.h, pow.cpp, primitives/transaction.h, protocol.h, spork.cpp, util.h, wallet/wallet.cpp` 

**Files in process:**
<hr>
@Mrs-X

**Done:**

- autogen.sh and configure scripts changed with files: `configure.ac, contrib/devtools/split-debug.sh,  libbitcoinconsensus.pc, qa/pull-tester/tests-config.sh, src/Makefile.am`

- pubkey issues: `pubkey.cpp, pubkey.h`
- rpcserver issues: `rpcserver.h`
- initialization: `init.cpp`
- misc: `addrman.*, arith_unit.h, chain.*, chainparams.h, hash.h, main.*, miner.cpp, net.cpp, block.h, transaction.h, txmempool.h, uint256.*, wallet.h`

**Files in process:**
1: **main.\*, net.cpp, miner.cpp, wallet.\*, obfuscation.h, txmempool.\*, rpcmining.cpp, validationinterface.h**

<hr>
@PIVX-Project

**Done:**
**Files in process:**
<hr>
@presstab

**Done:**
**Files in process:**
<hr>
...
<hr>
...
<hr>

**Comment by jonspock** [comment]
First commit
Use NetworkIDString as string instead of Enum NetworkID, some compilation fixes, some uint256 changes, remove some duplicate lines
  
   modified:   activemasternode.cpp
        modified:   chain.h
        modified:   chainparams.cpp
        modified:   chainparams.h
        modified:   chainparamsbase.h
        modified:   checkpoints.h
        modified:   coins.cpp
        modified:   coins.h
        modified:   compat/byteswap.h
        modified:   hash.h
        modified:   kernel.cpp
        modified:   main.cpp
        modified:   main.h
        modified:   masternode-budget.cpp
        modified:   masternode-budget.h
        modified:   masternode.cpp
        modified:   masternodeconfig.cpp
        modified:   masternodeman.cpp
        modified:   masternodeman.h
        modified:   net.h
        modified:   pow.cpp
        modified:   primitives/transaction.h
        modified:   protocol.h
        modified:   spork.cpp
        modified:   util.h
        modified:   wallet/wallet.cpp

------
I noticed duplicate wallet files. i.e in both src and src/wallet.cpp

Also had compile issues with keepass. Can we just take the latest from Dash, do we even do any customization there?

I assume all of the QT code shouldn't need much fussing with?

Some code included "darksend.h" or "dash-config.h" causing compile issues
This is a good stopping point for me.

**Comment by Mrs-X** [comment]
- src/wallet.cpp is the (Bitcoin) future.
- AFAIK there were no changes in keepass
- yes, there are tons of darksend/dash references I couldn't get rid of with the merging tool without losing other information from one side of the merge. Those need to be fixed/changed/removed (more precise: temporarily comment out) by hand.

**Comment by jonspock** [comment]
modified:   arith_uint256.h
        modified:   bip38.cpp
        modified:   chain.cpp
        modified:   chain.h
        modified:   chainparamsbase.cpp
        modified:   compat/byteswap.h
        modified:   compat/endian.h
        modified:   main.h
        modified:   pow.cpp
        modified:   uint256.cpp
        modified:   uint256.h
        modified:   util.h

Mostly uint256/arith_uint256

Since secp256k1 code changed, I had to comment out a couple of calls in BIP38 due to interface change. Looks like Doug worked on this originally. I will get back to it later.
Currently done for the day, will look at more tomorrow
